provider:
  name: faas
  gateway: 

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: alexellis/fn1:0.2
  ruby-test:
    lang: ruby
    handler: ./ruby-test
    image: alexellis/ruby-test:latest
