provider:
  name: faas
  gateway: http://localhost:8080

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: alexellis/fn1

  fn2:
    lang: go
    handler: ./fn2
    image: fn2
    environment:
      secret_name: "not-an-aws-key"
    secrets:
    - not-an-aws-key
