provider:
  name: faas
  gateway: 

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: alexellis2/fn1:0.4

  octo:
    lang: ruby
    handler: ./octo
    image: alexellis/octo:0.2

  ruby-test:
    lang: ruby
    handler: ./ruby-test
    image: alexellis2/ruby-test:0.1

  serve:
    lang: python3
    handler: ./serve
    image: alexellis/serve:latest
    environment:
       content_type: text/html
