provider:
  name: faas

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: alexellis2/fn1:0.2
    
  ruby-test:
    lang: ruby
    handler: ./ruby-test
    image: alexellis2/ruby-test:latest


